server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orangetalent2?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 99288723
  jpa:
    hibernate:
      ddl-auto: update
#  application:
#    name: todo-service